server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.josdem.io/
credentials:
  client: enter-your-client-here
  secret: enter-your-secret-here