server:
  port: 8081
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/
credentials:
  client: enter-your-client-here
  secret: enter-your-secret-here